config/routes.rb
RottenMangos::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace :admin do
    resources :users do
      post :impersonate, on: :member
      post :return, on: :collection 
    end
  end
  namespace :my do
    resources :reviews, only: [:index]
    resource :profile, only: [:edit, :update]
  end

  

end

app/controllers/my/base_controller.rb
class My::BaseController < ApplicationController

  before_filter :ensure_logged_in

  protected

  def ensure_logged_in
    redirect_to root_path, notice: 'Please Log In' unless current_user
  end

end

app/controllers/my/profiles_controller.rb
class My::ProfilesController < My::BaseController

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to edit_my_profile_path, notice: 'Profile edited.'
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname)
  end
end

app/controllers/my/reviews_controller.rb
class My::ReviewsController < My::BaseController

  def index
    @reviews = Review.where(user_id: current_user.id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

end

app/views/my/profiles/_form.html.erb
<div>
  <%= form.text_field :email %>
</div>
<div>
  <%= form.text_field :firstname %>
</div>
<div>
  <%= form.text_field :lastname %>
</div>

app/views/my/profiles/edit.html.erb
<h1> Edit Your Profile </h1>

<%= form_for @user, url: my_profile_path do |f| %>

  <%= render f %>
  <%= render 'extra_fields', f: f %>

  <%= f.submit 'Update' %>

<% end %>