config/routes.rb
RottenMangos::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace :admin do
    resources :users do
      post :impersonate, on: :member
      post :return, on: :collection 
    end
  end
  namespace :my do
    resources :reviews, only: [:index]
    resource :profile, only: [:edit, :update]
  end

  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    params[:search].blank? && params[:runtime_in_minutes].blank? ? @movies = Movie.all : @movies = Movie.search(params[:search]).search_runtime(params[:runtime_in_minutes])
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :remote_poster_url, :description, :poster
    )
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/views/movies/_movie_info.html.erb
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.poster_url(:thumb).to_s), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
  <p>Score: <%= movie.review_average %></p>
  <hr>
<% end %>

app/views/movies/_search.html.erb
<%= form_tag(movies_path, method: "get") do %>
  <%= label_tag(:search) %>
  <%= text_field_tag(:search, params[:search]) %>  
  <%= select_tag(:runtime_in_minutes, options_for_select([['', nil], ['Under 90','<90'], ['Between 90 and 120','90<x<120'], ['Over 120', '>120']]))%>
  <%= submit_tag "Search" , :name => nil %>
<% end %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>

<%= render 'search' %>

<hr>

<%= render 'movie_info' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_url(:banner).to_s), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>
<p>Score: <%= @movie.review_average %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small><%= link_to "#{review.user.full_name}", user_path(review.user) %> </small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>