config/routes.rb
RottenMangos::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace :admin do
    resources :users do
      post :impersonate, on: :member
      post :return, on: :collection 
    end
  end
  namespace :my do
    resources :reviews, only: [:index]
    resource :profile, only: [:edit, :update]
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true

  validates :firstname, presence: true

  validates :lastname, presence: true

  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      redirect_to admin_users_path, notice: "User: #{@user.full_name} created!"
    else
      render :new
    end
  end

  def index
    @users = User.all.page(params[:page]).per(3)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      if @user.destroy
        # Tell the UserMailer to send a welcome email after save
        UserMailer.goodbye_email(@user).deliver
 
        format.html { redirect_to admin_users_path, notice: "User: #{@user.full_name} deleted!" }
        format.json { render json: @user, status: :deleted, location: @user }
      else
        format.html { render action: 'index' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end 

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_later
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin_user_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin?" %>
    <%= f.check_box :admin %>
  </div>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_for @user, url: admin_user_path, html: { method: :put } do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin?" %>
    <%= f.check_box :admin %>
  </div>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Back to all users", admin_users_path %>

<h2>Edit a User</h2>
<%= render 'form' %>
<%= link_to "Delete", admin_user_path, method: "delete" %>

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Create a user.", new_admin_user_path %>
<hr>
<%= paginate @users %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Impersonate</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.full_name %></td>
    <td><%= user.email %></td>
    <td><%= link_to "Edit", edit_admin_user_path(user) %></td>
    <td><%= link_to "Delete", admin_user_path(user), method: "delete" %></td>
    <td><%= link_to "Impersonate", impersonate_admin_user_path(user), method: :post %></td>
  </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<%= link_to "Back to all users", admin_users_path %>

<h2>Create a User</h2>
<%= form_for @user, url: admin_users_path do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>


  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<h3><%= @user.full_name %></h3>
<ul>
  <li>First name: <%= @user.firstname %></li>
  <li>Last name: <%= @user.lastname %></li>
  <li>Email: <%= @user.email %></li>
</ul>
<%= link_to "Delete", admin_user_path(@user), method: "delete" %>
<%= link_to "Edit", edit_admin_user_path %>