config/routes.rb
RottenMangos::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'
  namespace :admin do
    resources :users do
      post :impersonate, on: :member
      post :return, on: :collection 
    end
  end
  namespace :my do
    resources :reviews, only: [:index]
    resource :profile, only: [:edit, :update]
  end

  

end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path, method: :delete %>)
      <% if current_user.admin? %>
        <%= link_to "Admin", admin_users_path %> | <%= link_to "Movies", movies_path %>
      <% end %>
      <% if !session[:admin_user_id].nil? %>
        <%= link_to "Back to Admin", return_admin_users_path, method: :post %>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>